spring.application.name=webinar-platform2
spring.datasource.url=jdbc:mysql://localhost:3306/webinar_db
spring.datasource.username=root
spring.datasource.password=Kishore@180711
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true